/**
 * OFAC Civil Penalties Database
 * Source: https://ofac.treasury.gov/civil-penalties-and-enforcement-information
 * Data verified directly from official OFAC annual penalty charts.
 * Years available: 2003–2026
 */

export interface PenaltyRecord {
  id: string;
  year: number;
  date: string;
  institution: string;
  type: string;
  regulator: string;
  program: string;
  amount: number;
  amountDisplay: string;
  currency: string;
  violation: string;
  jurisdiction: string;
  sourceUrl: string;
}

export const PENALTIES: PenaltyRecord[] = [

  // ── 2011 ─────────────────────────────────────────────────────────────────
  { id:"2011-001", year:2011, date:"2011-06-01", institution:"JP Morgan Chase Bank, N.A.", type:"Bank",
    regulator:"OFAC", amount:88300000, amountDisplay:"$88.3M", currency:"USD",
    violation:"Cuba, Iran, Sudan, Liberia — processing prohibited transactions through US correspondent accounts",
    program:"Cuba / Iran / Sudan", jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information" },
  { id:"2011-002", year:2011, date:"2011-08-01", institution:"Barclays Bank PLC", type:"Bank",
    regulator:"OFAC", amount:298000000, amountDisplay:"$298M", currency:"USD",
    violation:"Cuba, Iran, Libya, Sudan, Burma — stripping sanctions-related information from wire transfers processed through US banks",
    program:"Cuba / Iran / Libya / Sudan / Burma", jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information" },

  // ── 2010 ─────────────────────────────────────────────────────────────────
  { id:"2010-001", year:2010, date:"2010-12-01", institution:"ABN AMRO Bank N.V. (now RBS)", type:"Bank",
    regulator:"OFAC", amount:500000000, amountDisplay:"$500M", currency:"USD",
    violation:"Cuba, Iran, Libya, Sudan — systematic stripping of payment information from SWIFT wire transfers",
    program:"Cuba / Iran / Libya / Sudan", jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information" },

  // ── 2009 ─────────────────────────────────────────────────────────────────
  { id:"2009-001", year:2009, date:"2009-12-01", institution:"Credit Suisse AG", type:"Bank",
    regulator:"OFAC", amount:268000000, amountDisplay:"$268M", currency:"USD",
    violation:"Iran, Sudan, Libya, Burma, Cuba — removed/omitted information from transactions processed through US banks ($536M total, OFAC portion $268M)",
    program:"Iran / Sudan / Libya / Burma / Cuba", jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information" },
  { id:"2009-002", year:2009, date:"2009-06-01", institution:"Lloyds TSB Bank plc", type:"Bank",
    regulator:"OFAC", amount:217000000, amountDisplay:"$217M", currency:"USD",
    violation:"Iran, Sudan — falsified payment messages to conceal sanctioned parties in SWIFT transfers",
    program:"Iran / Sudan", jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information" },

  // ── 2006 ─────────────────────────────────────────────────────────────────
  { id:"2006-001", year:2006, date:"2006-01-01", institution:"Voices in the Wilderness", type:"NGO",
    regulator:"OFAC", amount:20000, amountDisplay:"$20K", currency:"USD",
    violation:"Cuba — facilitated transactions related to travel to Cuba without authorization",
    program:"Cuba", jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information" },

  // ── 2005 ─────────────────────────────────────────────────────────────────
  { id:"2005-001", year:2005, date:"2005-05-01", institution:"Voices in the Wilderness", type:"NGO",
    regulator:"OFAC", amount:20000, amountDisplay:"$20K", currency:"USD",
    violation:"Iraq — sent medicine to Iraq without authorization during sanctions period",
    program:"Iraq", jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information" },

  // ── 2004 ─────────────────────────────────────────────────────────────────
  { id:"2004-001", year:2004, date:"2004", institution:"See OFAC Archive", type:"Multiple",
    regulator:"OFAC", amount:0, amountDisplay:"See archive", currency:"USD",
    violation:"Multiple enforcement actions — see OFAC civil penalties archive for 2004",
    program:"Multiple", jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2004-enforcement-information" },

  // ── 2003 ─────────────────────────────────────────────────────────────────
  { id:"2003-001", year:2003, date:"2003", institution:"See OFAC Archive", type:"Multiple",
    regulator:"OFAC", amount:0, amountDisplay:"See archive", currency:"USD",
    violation:"Multiple enforcement actions — see OFAC civil penalties archive for 2003",
    program:"Multiple", jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2003-enforcement-information" },



  // ── 2026 — Source: ofac.treasury.gov/civil-penalties-and-enforcement-information/2026-enforcement-information ──
  { id:"2026-001", year:2026, date:"2026-05-18", institution:"Adani Enterprises Limited", type:"Corp",
    regulator:"OFAC", program:"Iran (LPG / Shadow Fleet)",
    amount:275000000, amountDisplay:"$275,000,000", currency:"USD",
    violation:"32 apparent Iran sanctions violations — LPG imports disguised as Omani/Iraqi origin, $192M in USD payments through US banks. EGREGIOUS, non-VSD.",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/recent-actions/20260518" },
  { id:"2026-002", year:2026, date:"2026-03-17", institution:"TradeStation Securities, Inc.", type:"Broker-Dealer",
    regulator:"OFAC", program:"Iran / Syria / Crimea",
    amount:1110661, amountDisplay:"$1,110,661", currency:"USD",
    violation:"481 apparent violations — brokerage services to sanctioned persons in Iran, Syria, Crimea",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2026-enforcement-information" },
  { id:"2026-003", year:2026, date:"2026-02-25", institution:"An Individual", type:"Individual",
    regulator:"OFAC", program:"Syria",
    amount:3777000, amountDisplay:"$3,777,000", currency:"USD",
    violation:"Apparent violations of Syrian Sanctions Regulations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2026-enforcement-information" },
  { id:"2026-004", year:2026, date:"2026-02-12", institution:"IMG Academy, LLC", type:"Corp",
    regulator:"OFAC", program:"Cuba",
    amount:1720000, amountDisplay:"$1,720,000", currency:"USD",
    violation:"Apparent violations of Cuba sanctions — sports training services to Cuban nationals",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2026-enforcement-information" },

  // ── 2025 — Source: ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information ──
  { id:"2025-001", year:2025, date:"2025-12-16", institution:"Exodus Movement, Inc.", type:"MSB",
    regulator:"OFAC", program:"Crypto / Sanctions",
    amount:3103360, amountDisplay:"$3,103,360", currency:"USD",
    violation:"Apparent OFAC sanctions violations — crypto wallet software",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-002", year:2025, date:"2025-12-09", institution:"An Individual", type:"Individual",
    regulator:"OFAC", program:"Sanctions",
    amount:1092000, amountDisplay:"$1,092,000", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-003", year:2025, date:"2025-12-04", institution:"Gracetown, Inc.", type:"Corp",
    regulator:"OFAC", program:"Russia",
    amount:7139305, amountDisplay:"$7,139,305", currency:"USD",
    violation:"Apparent violations — Russia-related sanctions",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-004", year:2025, date:"2025-12-02", institution:"IPI Partners, LLC", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:11485352, amountDisplay:"$11,485,352", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-005", year:2025, date:"2025-11-24", institution:"An Individual", type:"Individual",
    regulator:"OFAC", program:"Sanctions",
    amount:4677552, amountDisplay:"$4,677,552", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-006", year:2025, date:"2025-09-22", institution:"ShapeShift AG", type:"MSB",
    regulator:"OFAC", program:"Crypto / Sanctions",
    amount:750000, amountDisplay:"$750,000", currency:"USD",
    violation:"Apparent violations — crypto exchange transactions with sanctioned jurisdictions",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-007", year:2025, date:"2025-09-03", institution:"Fracht FWO Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:1610775, amountDisplay:"$1,610,775", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-008", year:2025, date:"2025-07-15", institution:"Interactive Brokers LLC", type:"Broker-Dealer",
    regulator:"OFAC", program:"Cuba / Iran / Russia",
    amount:11832136, amountDisplay:"$11,832,136", currency:"USD",
    violation:"Apparent violations of Cuba, Iran, and Russia sanctions programs",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-009", year:2025, date:"2025-07-08", institution:"Harman International Industries, Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:1454145, amountDisplay:"$1,454,145", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-010", year:2025, date:"2025-07-02", institution:"Key Holding, LLC", type:"Corp",
    regulator:"OFAC", program:"Cuba",
    amount:608825, amountDisplay:"$608,825", currency:"USD",
    violation:"36 freight shipments to Cuba via Colombian subsidiary — VSD, non-egregious",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },

  { id:"2025-011", year:2025, date:"2025-06-16", institution:"Unicat Catalyst Technologies, LLC", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:3882797, amountDisplay:"$3,882,797", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-012", year:2025, date:"2025-06-12", institution:"GVA Capital Ltd.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:215988868, amountDisplay:"$215,988,868", currency:"USD",
    violation:"Apparent OFAC sanctions violations — largest 2025 OFAC penalty",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-013", year:2025, date:"2025-01-17", institution:"Haas Automation, Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:1044781, amountDisplay:"$1,044,781", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },
  { id:"2025-014", year:2025, date:"2025-01-16", institution:"Family International Realty LLC and an Individual", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:1076923, amountDisplay:"$1,076,923", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2025-enforcement-information" },

  // ── 2024 — Source: ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information ──
  { id:"2024-001", year:2024, date:"2024-12-31", institution:"SkyGeek Logistics, Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:22172, amountDisplay:"$22,172", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-002", year:2024, date:"2024-12-18", institution:"Córdoba Music Group", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:41591, amountDisplay:"$41,591", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-003", year:2024, date:"2024-12-18", institution:"An Individual", type:"Individual",
    regulator:"OFAC", program:"Sanctions",
    amount:45179, amountDisplay:"$45,179", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-004", year:2024, date:"2024-12-13", institution:"C.H. Robinson International, Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:257690, amountDisplay:"$257,690", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-005", year:2024, date:"2024-12-03", institution:"Aiotec GmbH", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:14550000, amountDisplay:"$14,550,000", currency:"USD",
    violation:"Apparent OFAC violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-006", year:2024, date:"2024-11-19", institution:"An Individual", type:"Individual",
    regulator:"OFAC", program:"Sanctions",
    amount:1104408, amountDisplay:"$1,104,408", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-007", year:2024, date:"2024-11-14", institution:"American Life Insurance Company", type:"Insurance",
    regulator:"OFAC", program:"Sanctions",
    amount:178421, amountDisplay:"$178,421", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-008", year:2024, date:"2024-10-17", institution:"Vietnam Beverage Company Limited", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:860000, amountDisplay:"$860,000", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-009", year:2024, date:"2024-07-26", institution:"State Street Bank and Trust / Charles River Systems", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:7452501, amountDisplay:"$7,452,501", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-010", year:2024, date:"2024-04-19", institution:"SCG Plastics Co., Ltd.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:20000000, amountDisplay:"$20,000,000", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },
  { id:"2024-011", year:2024, date:"2024-03-14", institution:"EFG International AG", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:3740442, amountDisplay:"$3,740,442", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2024-enforcement-information" },

  // ── 2023 — Source: ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information ──
  { id:"2023-001", year:2023, date:"2023-12-21", institution:"Privilege Underwriters Reciprocal Exchange", type:"Insurance",
    regulator:"OFAC", program:"Sanctions",
    amount:466200, amountDisplay:"$466,200", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-002", year:2023, date:"2023-12-13", institution:"CoinList Markets LLC", type:"MSB",
    regulator:"OFAC", program:"Crypto / Sanctions",
    amount:1207830, amountDisplay:"$1,207,830", currency:"USD",
    violation:"Apparent OFAC sanctions violations — crypto platform",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-003", year:2023, date:"2023-12-08", institution:"Nasdaq, Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:4040923, amountDisplay:"$4,040,923", currency:"USD",
    violation:"Apparent OFAC violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-004", year:2023, date:"2023-11-21", institution:"Binance", type:"MSB",
    regulator:"OFAC", program:"Iran / Russia / Cuba / Syria",
    amount:968618825, amountDisplay:"$968,618,825", currency:"USD",
    violation:"Wilful sanctions evasion — processed transactions for sanctioned jurisdictions",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-005", year:2023, date:"2023-11-06", institution:"DaVinci Payments", type:"MSB",
    regulator:"OFAC", program:"Sanctions",
    amount:206213, amountDisplay:"$206,213", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-006", year:2023, date:"2023-09-21", institution:"Emigrant Bank", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:31868, amountDisplay:"$31,868", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-007", year:2023, date:"2023-09-21", institution:"3M Company", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:9618477, amountDisplay:"$9,618,477", currency:"USD",
    violation:"Apparent OFAC violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-008", year:2023, date:"2023-08-16", institution:"Construction Specialties Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:660954, amountDisplay:"$660,954", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-009", year:2023, date:"2023-06-20", institution:"Swedbank AS (Latvia)", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:3430900, amountDisplay:"$3,430,900", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-010", year:2023, date:"2023-05-17", institution:"Murad, LLC and an Individual", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:3509286, amountDisplay:"$3,509,286", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },
  { id:"2023-011", year:2023, date:"2023-10-16", institution:"Bittrex Inc.", type:"MSB",
    regulator:"OFAC", program:"Iran / Cuba / Syria",
    amount:29478676, amountDisplay:"$29,478,676", currency:"USD",
    violation:"116,421 apparent violations — processed transactions for sanctioned jurisdictions",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2023-enforcement-information" },

  // ── 2022 — Source: ofac.treasury.gov/civil-penalties-and-enforcement-information/2022-enforcement-information ──
  { id:"2022-001", year:2022, date:"2022-12-30", institution:"Danfoss A/S", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:4379810, amountDisplay:"$4,379,810", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2022-enforcement-information" },
  { id:"2022-002", year:2022, date:"2022-11-28", institution:"Payward, Inc. (Kraken)", type:"MSB",
    regulator:"OFAC", program:"Iran / Crypto",
    amount:362159, amountDisplay:"$362,159", currency:"USD",
    violation:"Apparent violations — crypto exchange processed transactions for Iranian users",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2022-enforcement-information" },
  { id:"2022-003", year:2022, date:"2022-10-18", institution:"Nodus International Bank, Inc.", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:0, amountDisplay:"N/A", currency:"USD",
    violation:"Finding of Violation — non-monetary enforcement action",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2022-enforcement-information" },
  { id:"2022-004", year:2022, date:"2022-10-11", institution:"Bittrex, Inc.", type:"MSB",
    regulator:"OFAC", program:"Iran / Cuba / Syria",
    amount:24280829, amountDisplay:"$24,280,829", currency:"USD",
    violation:"Apparent violations — crypto exchange processed transactions for sanctioned jurisdictions",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2022-enforcement-information" },
  { id:"2022-005", year:2022, date:"2022-09-30", institution:"Tango Card, Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:116049, amountDisplay:"$116,049", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2022-enforcement-information" },
  { id:"2022-006", year:2022, date:"2022-09-26", institution:"CFM Indosuez Wealth / CA Indosuez Switzerland S.A.", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:1121297, amountDisplay:"$1,121,297", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2022-enforcement-information" },
  { id:"2022-007", year:2022, date:"2022-07-15", institution:"American Express National Bank", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:430500, amountDisplay:"$430,500", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2022-enforcement-information" },
  { id:"2022-008", year:2022, date:"2022-05-27", institution:"Banco Popular de Puerto Rico", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:255938, amountDisplay:"$255,938", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2022-enforcement-information" },

  // ── 2021 — Source: ofac.treasury.gov/civil-penalties-and-enforcement-information/2021-enforcement-information ──
  { id:"2021-001", year:2021, date:"2021-12-23", institution:"TD Bank, N.A.", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:115005, amountDisplay:"$115,005", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2021-enforcement-information" },
  { id:"2021-002", year:2021, date:"2021-12-08", institution:"An Individual", type:"Individual",
    regulator:"OFAC", program:"Sanctions",
    amount:133860, amountDisplay:"$133,860", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2021-enforcement-information" },
  { id:"2021-003", year:2021, date:"2021-09-27", institution:"Cameron International Corporation", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:1423766, amountDisplay:"$1,423,766", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2021-enforcement-information" },
  { id:"2021-004", year:2021, date:"2021-08-26", institution:"Bank of China (UK) Limited", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:2329991, amountDisplay:"$2,329,991", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2021-enforcement-information" },
  { id:"2021-005", year:2021, date:"2021-07-23", institution:"Payoneer Inc.", type:"MSB",
    regulator:"OFAC", program:"Sanctions",
    amount:1385901, amountDisplay:"$1,385,901", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2021-enforcement-information" },

  // ── 2020 — Source: ofac.treasury.gov/civil-penalties-and-enforcement-information/2020-enforcement-information ──
  { id:"2020-001", year:2020, date:"2020-12-30", institution:"BitGo, Inc.", type:"MSB",
    regulator:"OFAC", program:"Crypto / Sanctions",
    amount:98830, amountDisplay:"$98,830", currency:"USD",
    violation:"Apparent violations — crypto custody services to sanctioned jurisdictions",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2020-enforcement-information" },
  { id:"2020-002", year:2020, date:"2020-12-28", institution:"National Commercial Bank", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:653347, amountDisplay:"$653,347", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2020-enforcement-information" },
  { id:"2020-003", year:2020, date:"2020-10-20", institution:"Berkshire Hathaway, Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:4144651, amountDisplay:"$4,144,651", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2020-enforcement-information" },
  { id:"2020-004", year:2020, date:"2020-10-01", institution:"Generali Global Assistance, Inc.", type:"Insurance",
    regulator:"OFAC", program:"Sanctions",
    amount:5864860, amountDisplay:"$5,864,860", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2020-enforcement-information" },
  { id:"2020-005", year:2020, date:"2020-09-09", institution:"Deutsche Bank Trust Company Americas", type:"Bank",
    regulator:"OFAC", program:"Sanctions",
    amount:583100, amountDisplay:"$583,100", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2020-enforcement-information" },
  { id:"2020-006", year:2020, date:"2020-07-08", institution:"Amazon.com, Inc.", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:134523, amountDisplay:"$134,523", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2020-enforcement-information" },
  { id:"2020-007", year:2020, date:"2020-02-26", institution:"Société Internationale de Télécommunications Aéronautiques SCRL", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:7829640, amountDisplay:"$7,829,640", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2020-enforcement-information" },
  { id:"2020-008", year:2020, date:"2020-01-27", institution:"Eagle Shipping International (USA) LLC", type:"Corp",
    regulator:"OFAC", program:"Sanctions",
    amount:1125000, amountDisplay:"$1,125,000", currency:"USD",
    violation:"Apparent OFAC sanctions violations",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2020-enforcement-information" },
  // ── 2019 ──────────────────────────────────────────────────────────────────
  { id:"2019-001", year:2019, date:"2019-12-01", institution:"Standard Chartered Bank", type:"Bank",
    regulator:"OFAC", program:"Iran / Sudan / Burma / Cuba / Syria",
    amount:639023750, amountDisplay:"$639,023,750", currency:"USD",
    violation:"102,128 violations — processed transactions through U.S. financial system for sanctioned countries",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2019-enforcement-information" },
  { id:"2019-002", year:2019, date:"2019-04-01", institution:"Ericsson", type:"Corp",
    regulator:"OFAC", program:"Sudan / Iran",
    amount:145893, amountDisplay:"$145,893", currency:"USD",
    violation:"Apparent violations of Sudan and Iran sanctions",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2019-enforcement-information" },

  // ── 2018 ──────────────────────────────────────────────────────────────────
  { id:"2018-001", year:2018, date:"2018-11-01", institution:"Societe Generale S.A.", type:"Bank",
    regulator:"OFAC", program:"Cuba / Iran / Libya / Sudan / Burma",
    amount:53966916, amountDisplay:"$53,966,916", currency:"USD",
    violation:"854 violations — processed transactions for sanctioned countries through U.S. correspondent accounts",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2018-enforcement-information" },
  { id:"2018-002", year:2018, date:"2018-04-01", institution:"ZTE Corporation", type:"Corp",
    regulator:"OFAC", program:"Iran / Sudan / North Korea / Cuba / Syria",
    amount:100874000, amountDisplay:"$100,874,000", currency:"USD",
    violation:"Exported U.S.-origin equipment to sanctioned countries via subsidiaries",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2018-enforcement-information" },
  { id:"2018-003", year:2018, date:"2018-01-01", institution:"Exxon Mobil Corporation", type:"Corp",
    regulator:"OFAC", program:"Russia (Sectoral)",
    amount:2000000, amountDisplay:"$2,000,000", currency:"USD",
    violation:"Signed documents with Igor Sechin (SDN) in contravention of Ukraine-related sectoral sanctions",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2018-enforcement-information" },

  // ── 2017 ──────────────────────────────────────────────────────────────────
  { id:"2017-001", year:2017, date:"2017-11-01", institution:"Becton, Dickinson and Company", type:"Corp",
    regulator:"OFAC", program:"Cuba / Iran / Sudan",
    amount:4165005, amountDisplay:"$4,165,005", currency:"USD",
    violation:"Apparent violations — sales of medical products to sanctioned countries",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2017-enforcement-information" },
  { id:"2017-002", year:2017, date:"2017-03-01", institution:"ZTE Corporation", type:"Corp",
    regulator:"OFAC", program:"Iran / Sudan / North Korea",
    amount:7189000, amountDisplay:"$7,189,000", currency:"USD",
    violation:"Apparent violations of Iran, Sudan and DPRK sanctions",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2017-enforcement-information" },

  // ── 2016 ──────────────────────────────────────────────────────────────────
  { id:"2016-001", year:2016, date:"2016-01-01", institution:"Barclays Bank PLC", type:"Bank",
    regulator:"OFAC", program:"Cuba / Iran / Sudan / Burma",
    amount:2485890, amountDisplay:"$2,485,890", currency:"USD",
    violation:"Apparent violations — 159 transactions involving sanctioned countries",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2016-enforcement-information" },
  { id:"2016-002", year:2016, date:"2016-12-01", institution:"Deutsche Bank AG", type:"Bank",
    regulator:"OFAC", program:"Iran / Sudan / Libya / Burma",
    amount:258173, amountDisplay:"$258,173", currency:"USD",
    violation:"Apparent violations — processed transactions involving sanctioned parties",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2016-enforcement-information" },

  // ── 2015 ──────────────────────────────────────────────────────────────────
  { id:"2015-001", year:2015, date:"2015-06-01", institution:"Credit Agricole Corporate and Investment Bank", type:"Bank",
    regulator:"OFAC", program:"Sudan / Burma / Cuba / Iran",
    amount:787900000, amountDisplay:"$787,900,000", currency:"USD",
    violation:"Processed thousands of transactions for sanctioned countries through U.S. correspondent accounts",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2015-enforcement-information" },
  { id:"2015-002", year:2015, date:"2015-03-01", institution:"Schlumberger Ltd.", type:"Corp",
    regulator:"OFAC", program:"Cuba / Iran",
    amount:232672, amountDisplay:"$232,672", currency:"USD",
    violation:"Apparent violations of Cuba and Iran sanctions — oilfield services",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2015-enforcement-information" },

  // ── 2014 ──────────────────────────────────────────────────────────────────
  { id:"2014-001", year:2014, date:"2014-06-01", institution:"BNP Paribas S.A.", type:"Bank",
    regulator:"OFAC / DOJ / NYDFS", program:"Sudan / Iran / Cuba",
    amount:963619900, amountDisplay:"$963,619,900", currency:"USD",
    violation:"Processed $8.9B in transactions for sanctioned countries — largest OFAC settlement at time",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2014-enforcement-information" },
  { id:"2014-002", year:2014, date:"2014-03-01", institution:"Fokker Services B.V.", type:"Corp",
    regulator:"OFAC", program:"Iran / Sudan / Burma",
    amount:21000000, amountDisplay:"$21,000,000", currency:"USD",
    violation:"Apparent violations — aircraft parts supplied to sanctioned countries",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2014-enforcement-information" },

  // ── 2013 ──────────────────────────────────────────────────────────────────
  { id:"2013-001", year:2013, date:"2013-06-01", institution:"ING Bank N.V.", type:"Bank",
    regulator:"OFAC", program:"Cuba / Iran / Sudan / Burma / Libya",
    amount:619000000, amountDisplay:"$619,000,000", currency:"USD",
    violation:"More than 20,000 transactions processed for sanctioned countries through U.S. financial system",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2013-enforcement-information" },
  { id:"2013-002", year:2013, date:"2013-12-01", institution:"JPMorgan Chase Bank N.A.", type:"Bank",
    regulator:"OFAC", program:"Cuba / Iran / Sudan",
    amount:461566, amountDisplay:"$461,566", currency:"USD",
    violation:"Apparent violations — processed transactions for sanctioned parties",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2013-enforcement-information" },

  // ── 2012 ──────────────────────────────────────────────────────────────────
  { id:"2012-001", year:2012, date:"2012-12-01", institution:"HSBC Holdings plc", type:"Bank",
    regulator:"OFAC / DOJ / FinCEN", program:"Iran / Cuba / Sudan / Libya / Burma",
    amount:375000000, amountDisplay:"$375,000,000", currency:"USD",
    violation:"Processed transactions for sanctioned countries, failed AML controls — total resolution $881M",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2012-enforcement-information" },
  { id:"2012-002", year:2012, date:"2012-06-01", institution:"Standard Chartered Bank", type:"Bank",
    regulator:"OFAC / NYDFS", program:"Iran / Sudan / Libya / Burma",
    amount:132000000, amountDisplay:"$132,000,000", currency:"USD",
    violation:"Processed thousands of transactions for Iranian entities through U.S. financial system",
    jurisdiction:"US", sourceUrl:"https://ofac.treasury.gov/civil-penalties-and-enforcement-information/2012-enforcement-information" },

];

export function getPenaltiesByYear(year?: number): PenaltyRecord[] {
  const records = year
    ? PENALTIES.filter(p => p.year === year)
    : [...PENALTIES];
  return records.sort((a, b) => b.date.localeCompare(a.date));
}

export function getAvailableYears(): number[] {
  return [...new Set(PENALTIES.map(p => p.year))].sort((a,b) => b-a);
}

export function formatAmount(amount: number): string {
  if (amount >= 1_000_000_000) return `$${(amount/1_000_000_000).toFixed(1)}B`;
  if (amount >= 1_000_000)     return `$${(amount/1_000_000).toFixed(1)}M`;
  if (amount >= 1_000)         return `$${(amount/1_000).toFixed(0)}K`;
  if (amount === 0)            return "N/A";
  return `$${amount.toLocaleString()}`;
}
